### ISSUE TITLE
创维酷开系统6.1 安装失败

### ISSUE THREAD

**Issue by zsbai** [xausky/emby-for-kitkat#3]
我查了查酷开系统6.1也是安卓4.4，安装却提示older sdk，另一个电视盒子4.4的系统却可以安装成功
<img width="780" alt="image" src="https://user-images.githubusercontent.com/62942942/169738660-1cfc5a10-f96f-4d44-bbd4-8c85371f0cfc.png">

**Comment by xausky** [comment]
./adb shell getprop ro.build.version.sdk
 输出 19 的才是 4.4 你这个情况没看错的话可能是虚标了安卓版本

**Comment by zsbai** [comment]
> 

输出的是17..我麻了
十分感谢 折腾电视太累了
