### ISSUE TITLE
安卓4.4.2中无法正常使用

### ISSUE THREAD

**Issue by SaiOog** [xausky/emby-for-kitkat#6]
我在第一次打开此软件时软件可以正常运行，播放视频也正常，但后面再次尝试时就卡在登录完成后在主页面的加载界面，而且加载的圆环会停止转动，继续等待下去电视会花屏，只能退出，再次进入、重装后依旧如此，请问作者有办法解决吗？
另：如果这个问题没法解决的话，请问作者安卓4.4.2上有没有可替代emby的emby类似物？多谢！

**Comment by superkeyor** [comment]
尝试在android tv中清空一下程序数据。目前这个app是最好的解决方案。

**Comment by 277383761** [comment]
希望作者再反编译移植一个新版,哈哈.

**Comment by ajf12f** [comment]
希望作者再反编译移植一个新版,哈哈.

**Comment by xausky** [comment]
移植新版是不可能了，4.4 的破盒子被我丢了，咸鱼淘了个 9.0 的，贼舒服。

**Comment by 277383761** [comment]
不会是e900v22c吧? 这个的解码能力还不如电芯送的安卓4的盒子峰火hk680



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月25日(周一) 中午11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xausky/emby-for-kitkat] 安卓4.4.2中无法正常使用 (Issue #6)




 
移植新版是不可能了，4.4 的破盒子被我丢了，咸鱼淘了个 9.0 的，贼舒服。
